```{r call library}
library(tidyverse)
library(sf)
library(tmap)
library(janitor)
library(spatstat)
library(spdep)
library(RColorBrewer)
library(tmaptools)
library(here)
library(purrr)
library(ggplot2)
```

```{r load imd data and london shapefile}
imd <- read_csv(here("data/File_1_-_IMD2019_Index_of_Multiple_Deprivation (1).csv")) %>% 
  clean_names()

lsoa <- st_read(here("data/london_lsoa/LSOA_2011_London_gen_MHW.shp")) %>% 
  st_transform(., 27700) 

borough <- st_read(here("data/london_lsoa/London_Borough_Excluding_MHW.shp")) %>% 
  st_transform(., 27700)
```

```{r join imd with lsoa}
imd_join <- left_join(lsoa, imd, by = c("LSOA11CD" = "lsoa_code_2011" )) %>% 
  dplyr::select(LSOA11CD, index_of_multiple_deprivation_imd_rank, index_of_multiple_deprivation_imd_decile, geometry)

#write csv
#imd_join$wkt <- st_as_text(imd_join$geometry)

#convert sf object to a dataframe before using select
#imd_join_df <- as.data.frame(imd_join) %>%
#  dplyr::select(-geometry)

#write.csv(imd_join_df, "imd_with_geometry.csv", row.names = FALSE)

# add flipped decile column
max_imd_decile <- max(imd_join$index_of_multiple_deprivation_imd_decile)
imd_join <- imd_join %>%
  mutate(index_of_multiple_deprivation_imd_decile_flipped = max_imd_decile + 1 - index_of_multiple_deprivation_imd_decile)

summary(imd_join)
```

```{r plot the imd with decile}
#plot the data sets
imd_map <- ggplot(imd_join, aes(fill = index_of_multiple_deprivation_imd_decile_flipped)) +
  geom_sf(color = "transparent") +
  scale_fill_viridis_c(option = "D", direction = -1) +  
  labs(title = "Index of Multiple Deprivation ", fill = "IMD Decile") +

#combine with borough
  geom_sf(data = borough, color = "white", fill = NA, size = 0.5) +

# Remove the grid
  theme_void() +

# Add note
  annotate("text", x = -Inf, y = -Inf, hjust = 0, vjust = -0.25, 
         label = "Note: 1 is the least deprived, 10 is the most deprived",
         size = 3, color = "black")
  
imd_map
```
```{r}
ggsave("D:/Fajrun/MSc Plan/3. Universities/University College London/Lectures/T2 GEOG0162 CDV/W3/Cartography-Blog-2/output/IMD_map2.jpg", plot = imd_map, width = 6.25, height = 4.25, dpi = 200)

```








